<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <RootNamespace>DotsAndBoxes.Shared</RootNamespace>
    <AssemblyName>DotsAndBoxes.Shared</AssemblyName>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../../Assets/01_Main/02_Scripts/Shared/**/*.cs"
             Link="Shared/%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
</Project>